---
- name: Install Nginx
  become: true
  apt:
    name: "nginx"
    state: "present"
  notify: ["restart nginx"]

- name: Setup nginx vhost
  become: true
  template:
    src: yoursite.conf.tpl
    dest: /etc/nginx/sites-enabled/{{ server_name }}.conf
  notify: ["restart nginx"]
        

  