# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(serialize=False, primary_key=True)),
                ('hostIdentifier', models.CharField(max_length=30, blank=True)),
                ('hostIp', models.CharField(max_length=30, blank=True)),
                ('hostUsername', models.CharField(max_length=30, blank=True)),
                ('hostPassword', models.CharField(max_length=30, blank=True)),
                ('status', models.CharField(default='initiated', max_length=30)),
                ('hostDocker', models.CharField(max_length=30, blank=True)),
                ('hostNginx', models.CharField(max_length=30, blank=True)),
                ('hostMysql', models.CharField(max_length=30, blank=True)),
                ('hostMongo', models.CharField(max_length=30, blank=True)),
                ('mysqlUsername', models.CharField(max_length=50, blank=True)),
                ('mysqlPassword', models.CharField(max_length=50, blank=True)),
            ],
            options={
                'permissions': (('view_content', 'View content'),),
            },
        ),
        migrations.CreateModel(
            name='Ports',
            fields=[
                ('id', models.AutoField(serialize=False, primary_key=True)),
                ('port', models.CharField(max_length=30, blank=True)),
                ('status', models.CharField(max_length=30, blank=True)),
                ('projectname', models.CharField(max_length=30, blank=True)),
                ('ptype', models.CharField(max_length=30, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('requester', models.CharField(max_length=100, blank=True)),
                ('id', models.AutoField(serialize=False, primary_key=True)),
                ('platform', models.CharField(max_length=30, blank=True)),
                ('hostIp', models.CharField(max_length=30, blank=True)),
                ('envtype', models.CharField(max_length=30, blank=True)),
                ('project_name', models.CharField(unique=True, max_length=30, blank=True)),
                ('application_name', models.CharField(max_length=30, blank=True)),
                ('repo_type', models.CharField(max_length=256, blank=True)),
                ('git_url', models.CharField(max_length=256, blank=True)),
                ('git_token', models.CharField(max_length=256, blank=True)),
                ('git_username', models.CharField(max_length=256, blank=True)),
                ('git_branch', models.CharField(max_length=256, blank=True)),
                ('status', models.CharField(default='submitted', max_length=30)),
                ('approvedBy', models.CharField(max_length=256, blank=True)),
                ('UBUNTU_VERSION', models.CharField(max_length=256, blank=True)),
                ('PHP_VERSION', models.CharField(max_length=256, blank=True)),
                ('PHP_MODULES', models.CharField(max_length=256, blank=True)),
                ('fileopp', models.CharField(max_length=30, blank=True)),
                ('document', models.FileField(upload_to='documents/', blank=True)),
                ('NGINX_SERVER_ROOT_VALUE', models.CharField(max_length=500, blank=True)),
                ('NGINX_STATIC_CONTENT_ACCESS_LOG_VALUE', models.CharField(max_length=500, blank=True)),
                ('NGINX_STATIC_CONTENT_EXPIRES_VALUE', models.CharField(max_length=500, blank=True)),
                ('key1', models.CharField(max_length=100, blank=True)),
                ('value1', models.CharField(max_length=100, blank=True)),
                ('key2', models.CharField(max_length=100, blank=True)),
                ('value2', models.CharField(max_length=100, blank=True)),
                ('key3', models.CharField(max_length=100, blank=True)),
                ('value3', models.CharField(max_length=100, blank=True)),
                ('key4', models.CharField(max_length=100, blank=True)),
                ('value4', models.CharField(max_length=100, blank=True)),
                ('key5', models.CharField(max_length=100, blank=True)),
                ('value5', models.CharField(max_length=100, blank=True)),
                ('MONGO_INITDB_DATABASE_VALUE', models.CharField(max_length=500, blank=True)),
                ('MONGO_INITDB_ROOT_USERNAME_VALUE', models.CharField(max_length=500, blank=True)),
                ('MONGO_INITDB_ROOT_PASSWORD_VALUE', models.CharField(max_length=500, blank=True)),
                ('mongo_version', models.CharField(max_length=500, blank=True)),
                ('mysql_version', models.CharField(max_length=20, blank=True)),
                ('MYSQL_DATABASE_NAME_VALUE', models.CharField(max_length=100, blank=True)),
                ('MYSQL_ROOT_PASSWORD_VALUE', models.CharField(max_length=100, blank=True)),
                ('MYSQL_USER_NAME_VALUE', models.CharField(max_length=100, blank=True)),
                ('MYSQL_PASSWORD_VALUE', models.CharField(max_length=100, blank=True)),
                ('MYSQL_CLIENT_DEFAULT_CHARACTER_SET_VALUE', models.CharField(max_length=100, blank=True)),
                ('varnish_version', models.CharField(max_length=100, blank=True)),
                ('VARNISH_BACKEND_HOST_VALUE', models.CharField(max_length=100, blank=True)),
                ('VARNISH_BACKEND_PORT_VALUE', models.CharField(max_length=100, blank=True)),
                ('VARNISH_PORT_VALUE', models.CharField(max_length=100, blank=True)),
                ('redis_version', models.CharField(max_length=100, blank=True)),
                ('REDIS_PASSWORD_VALUE', models.CharField(max_length=100, blank=True)),
            ],
            options={
                'permissions': (('view_content', 'View content'),),
            },
        ),
        migrations.CreateModel(
            name='runningstack',
            fields=[
                ('id', models.AutoField(serialize=False, primary_key=True)),
                ('projectname', models.CharField(max_length=50, blank=True)),
                ('status', models.CharField(max_length=50, blank=True)),
                ('url', models.CharField(max_length=50, blank=True)),
                ('urlStatus', models.CharField(max_length=50, blank=True)),
                ('hostIp', models.CharField(max_length=50, blank=True)),
                ('hostStatus', models.CharField(max_length=50, blank=True)),
                ('nginxport', models.CharField(max_length=50, blank=True)),
                ('varnishport', models.CharField(max_length=50, blank=True)),
                ('mysqluname', models.CharField(max_length=50, blank=True)),
                ('mysqlupwd', models.CharField(max_length=50, blank=True)),
                ('mysqlstatus', models.CharField(max_length=50, blank=True)),
                ('mongouname', models.CharField(max_length=50, blank=True)),
                ('mongoupwd', models.CharField(max_length=50, blank=True)),
                ('mongostatus', models.CharField(max_length=50, blank=True)),
                ('approvedBy', models.CharField(max_length=256, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.AutoField(serialize=False, primary_key=True)),
                ('projectname', models.CharField(max_length=1000, blank=True)),
                ('sshstatus', models.CharField(max_length=1000, blank=True)),
                ('dockerstatus', models.CharField(max_length=1000, blank=True)),
                ('urlstatus', models.CharField(max_length=1000, blank=True)),
                ('mongostatus', models.CharField(max_length=1000, blank=True)),
                ('mysqlstatus', models.CharField(max_length=1000, blank=True)),
            ],
        ),
    ]
