# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-25 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='mongoPassword',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='host',
            name='mongoUsername',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
