# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-05 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='host_Info',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
