# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-11 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ports',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('port', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(blank=True, max_length=30)),
                ('projectname', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
