# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-09 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='MONGO_PORT_VALUE',
        ),
        migrations.RemoveField(
            model_name='project',
            name='MYSQL_DUMP_MAX_ALLOWED_PACKET',
        ),
        migrations.RemoveField(
            model_name='project',
            name='MYSQL_PORT_VALUE',
        ),
        migrations.RemoveField(
            model_name='project',
            name='NGINX_BACKEND_HOST_VALUE',
        ),
        migrations.RemoveField(
            model_name='project',
            name='NGINX_SERVER_NAME_VALUE',
        ),
    ]
