# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-20 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='mongoname',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='status',
            name='mongost',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='status',
            name='mysqlname',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='status',
            name='mysqlst',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='status',
            name='nginxname',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='status',
            name='nginxst',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='status',
            name='redisname',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='status',
            name='redisst',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='status',
            name='varnishname',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='status',
            name='varnishst',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
