# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-13 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20180712_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
