# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-17 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_nameform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='nameform',
        ),
        migrations.AddField(
            model_name='status',
            name='mongoid',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='status',
            name='mysqlid',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='status',
            name='nginxid',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='status',
            name='nginxstatus',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='status',
            name='redisid',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='status',
            name='redisstatus',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='status',
            name='varnishid',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='status',
            name='varnishstatus',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
