# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-26 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20180725_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='hostIp',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
