# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-12 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_project_fileopp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='document',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
    ]
