# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-05 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_project_host_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='host_Info',
        ),
    ]
