# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-12 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20180712_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='approvedBy',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
