# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-13 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20180713_0655'),
    ]

    operations = [
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('projectname', models.CharField(blank=True, max_length=50)),
                ('sshstatus', models.CharField(blank=True, max_length=50)),
                ('dockerstatus', models.CharField(blank=True, max_length=50)),
                ('urlstatus', models.CharField(blank=True, max_length=50)),
                ('mongostatus', models.CharField(blank=True, max_length=50)),
                ('mysqlstatus', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
