# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-12 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_project_approvedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='runningstack',
            name='approvedBy',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
