# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-13 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_runningstack_approvedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='hostDocker',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='host',
            name='hostMongo',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='host',
            name='hostMysql',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='host',
            name='hostNginx',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
