# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_project_git_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='jenkins_status',
            field=models.CharField(default='Requested', max_length=256),
        ),
        migrations.AddField(
            model_name='project',
            name='mongo_status',
            field=models.CharField(default='Requested', max_length=256),
        ),
        migrations.AddField(
            model_name='project',
            name='mysql_status',
            field=models.CharField(default='Requested', max_length=256),
        ),
    ]
