# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-13 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20180713_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='mysqlPassword',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='host',
            name='mysqlUsername',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
