# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-02 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20180629_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='requester',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
