# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester', models.CharField(max_length=30)),
                ('project_name', models.CharField(max_length=30, unique=True)),
                ('application_name', models.CharField(max_length=30)),
                ('git_url', models.CharField(max_length=256)),
                ('platform_version', models.CharField(blank=True, max_length=30)),
                ('cpu', models.IntegerField(blank=True)),
                ('memory', models.IntegerField(blank=True)),
                ('build_tool', models.CharField(blank=True, max_length=30)),
                ('mysql_password', models.CharField(blank=True, max_length=30)),
                ('mongo_password', models.CharField(blank=True, max_length=30)),
                ('env_key1', models.CharField(blank=True, max_length=30)),
                ('env_value1', models.CharField(blank=True, max_length=500)),
                ('env_key2', models.CharField(blank=True, max_length=30)),
                ('env_value2', models.CharField(blank=True, max_length=500)),
                ('env_key3', models.CharField(blank=True, max_length=30)),
                ('env_value3', models.CharField(blank=True, max_length=500)),
                ('env_key4', models.CharField(blank=True, max_length=30)),
                ('env_value4', models.CharField(blank=True, max_length=500)),
                ('env_key5', models.CharField(blank=True, max_length=30)),
                ('env_value5', models.CharField(blank=True, max_length=500)),
                ('env_key6', models.CharField(blank=True, max_length=30)),
                ('env_value6', models.CharField(blank=True, max_length=500)),
                ('env_key7', models.CharField(blank=True, max_length=30)),
                ('env_value7', models.CharField(blank=True, max_length=500)),
                ('env_key8', models.CharField(blank=True, max_length=30)),
                ('env_value8', models.CharField(blank=True, max_length=500)),
                ('env_key9', models.CharField(blank=True, max_length=30)),
                ('env_value9', models.CharField(blank=True, max_length=500)),
                ('env_key10', models.CharField(blank=True, max_length=30)),
                ('env_value10', models.CharField(blank=True, max_length=500)),
                ('project_flag', models.BooleanField(default=False)),
            ],
        ),
    ]
