# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20171007_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='git_branch',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
