#jinja2: lstrip_blocks: True
version: '2.0'
services:
  {% if mysql.enable==true %}
   mysql:  
     image: mysql:{{ mysql.envi.mysql_version }}
     container_name: '{{ user.project_name }}_MYSQL' 
     volumes:
       - ./mysql:/var/lib/mysql
       - ./logs/mysql:/var/log/mysql
     environment:
       {% for key,value in mysql.envi.iteritems() %}
       {{ key }} : {{ value }}
       {% endfor %}
       
  {% endif %} 
  
  {% if mongodb.enable==true %}
   mongodb:
     image: mongo
     container_name: '{{ user.project_name }}_MongoDB'
     environment:
       {% for key,value in mongodb.envi.iteritems() %}
       {{ key }} : {{ value }}
       {% endfor %}
       
     volumes:
       - ./mongodb:/data/db
       - ./logs/mongodb:/var/log/mongodb
  {% endif %}

   

  {% if redis.enable==true %}
   redis:
     image: wodby/redis
     container_name: '{{ user.project_name }}_Redis' 
     environment:
       {% for key,value in redis.envi.iteritems() %}
       {{ key }} : {{ value }}
       {% endfor %}
       
  {% endif %}

  
  {% if nginx_php.enable==true %}
   nginx_php:
     image: webdevops/php-nginx:{{ nginx_php.envi.PHP_VERSION }}
     container_name: '{{ user.project_name }}_NGINX'
     environment:
       LOG_STDOUT: /var/log/nginx/access.log
       LOG_STDERR: /var/log/nginx/error.log
       {% for key,value in nginx_php.envi.iteritems() %}
       {{ key }} : {{ value }}
       {% endfor %}
     ports:
       - "{{ nginx_php.ports }}:80"
     volumes:
      - ./code:/var/www/html
      - ./logs/nginx:/var/log/nginx
          
  {% endif %}    
  
  {% if varnish.enable==true %} 
   varnish:
     image: wodby/varnish
     container_name: '{{ user.project_name }}_Varnish'
     environment:
       {% for key,value in varnish.envi.iteritems() %}
       {{ key }} : {{ value }}
       {% endfor %}
       
     depends_on:
       - nginx_php
     ports:
       - "{{ varnish.ports }}:6081"    

  {% endif %}

volumes:
    mysql:
    code:
    mongodb:
    logs: