#jinja2: lstrip_blocks: True
version: '3.0'
services:
  {% if mysql.enable==true %}
   mysql:  
     image: mysql:5.7
     volumes:
       - ./mysql:/var/lib/mysql
     environment:
       {% for key,value in mysql.envi.iteritems() %}
       {{ key }} : {{ value }}
       {% endfor %}
     ports:
       - "{{ mysql.ports }}:3306" 
       
  {% endif %} 
  
  {% if mongodb.enable==true %}
   mongodb:
     image: mongo
     environment:
       {% for key,value in mongodb.envi.iteritems() %}
       {{ key }} : {{ value }}
       {% endfor %}
       
     volumes:
       - ./mongodb:/data/db
       - ./logs/mongodb:/var/log/mongodb
     ports:
       - "{{ mongodb.ports }}:27017"
  {% endif %}

   

  {% if redis.enable==true %}
   redis:
     image: wodby/redis 
     environment:
       {% for key,value in redis.envi.iteritems() %}
       {{ key }} : {{ value }}
       {% endfor %}
       
  {% endif %}

  
  {% if nginx_php.enable==true %}
   nginx_php:
     image: pranjaljn97/php-nginx-ssh
     environment:
       {% for key,value in nginx_php.envi.iteritems() %}
       {{ key }} : {{ value }}
       {% endfor %}
     ports:
       - "{{ nginx_php.ports }}:80"
       - "{{ nginx_php.sshport }}:22"
     volumes:
      - ./code:/var/www/html
          
  {% endif %}    
  
  {% if varnish.enable==true %} 
   varnish:
     image: wodby/varnish
     environment:
       {% for key,value in varnish.envi.iteritems() %}
       {{ key }} : {{ value }}
       {% endfor %}
       
     depends_on:
       - nginx_php
     ports:
       - "{{ varnish.ports }}:6081"    

  {% endif %}

volumes:
    mysql:
    code:
    mongodb:
    logs:
