---
- name: Initial Task
  hosts: localhost
  connection: local
  sudo: yes
  roles: 
    - add-hosts
    
- name: New instances
  hosts: "{{ hostIp }}"
  become_user: root
  vars:
    ansible_sudo_pass: "{{ hostPassword }}"
    ansible_ssh_user: "{{ hostUsername }}"
    ansible_ssh_pass: "{{ hostPassword }}"
  roles:
    - docker-install
    - mysql
    - mongodb
